apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: plans.meter.servicefabrik.io
spec:
  group: meter.servicefabrik.io
  names:
    kind: Plan
    plural: plans
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            planId:
              type: string
            serviceId:
              type: string
            planName:
              type: string
            serviceName:
              type: string
            options:
              type: string
          type: object
        status:
          properties:
            state:
              type: string
          type: object
      type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null

